global:
  scrape_interval: 15s # Default is every 1 minute.
  evaluation_interval: 15s # The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - "localhost:9090" # prometheus itself

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "node-exporter:9100" # node-exporter